#!/usr/bin/env bash

# Checks that zsh version is provided as first argument.
if [ -z "${1}" ]; then
    echo "Please provide zsh version."
    exit 1
fi
VERSION="${1}"

# Downloads zsh tarball to temporary directory.
PACKAGE_NAME="zsh-${VERSION}.tar.gz"
TEMP_DIR="$(mktemp -d)"
DOWNLOAD_LOCATION="${TEMP_DIR}/zsh-${VERSION}.tar.gz"
echo "Downloading ${PACKAGE_NAME}..."
curl -o "${DOWNLOAD_LOCATION}" -L "https://sourceforge.net/projects/zsh/files/zsh/${VERSION}/zsh-${VERSION}.tar.xz/download"

# Checks that download succeeded.
if [ ${?} -ne 0 ]; then
    echo "Download failed."
    exit 1
fi

# Unpacks the downloaded tarball, then deletes it.
tar -C "${TEMP_DIR}" -xf "${DOWNLOAD_LOCATION}"
UNPACK_STATUS=${?}
rm -f "${DOWNLOAD_LOCATION}"

# Checks that unpacking succeeded.
if [ "${UNPACK_STATUS}" -ne 0 ]; then
    echo "Unpacking failed."
    exit 1
fi

# Installs zsh from unpacked files.
UNPACK_LOCATION="${TEMP_DIR}/zsh-${VERSION}"
pushd "${UNPACK_LOCATION}"
./configure && make && make test && sudo make install
INSTALLATION_STATUS=${?}
popd
rm -rf "${UNPACK_LOCATION}"

# Checks that installation succeeded.
if [ "${INSTALLATION_STATUS}" -ne 0 ]; then
    echo "Installation failed."
    exit 1
fi

# Sets zsh as default shell.
ZSH_LOCATION="$(command -v zsh)"
"${ZSH_LOCATION}" | sudo tee -a /etc/shells && chsh -s "${ZSH_LOCATION}"
if [ "${?}" -ne 0 ]; then
    echo "zsh installation succeeded, but failed to set it as default shell."
    exit 1
fi

# Installs zsh-autosuggestions.
git clone https://github.com/zsh-users/zsh-autosuggestions "${HOME}/.zsh/zsh-autosuggestions"

echo "Installed zsh-${VERSION} and set it as default shell."
exit 0
