#!/usr/bin/env bash

# Installs zsh-autosuggestions plugin
echo "Installing zsh-autosuggestions..."
git clone --depth 1 --branch v0.7.0 https://github.com/zsh-users/zsh-autosuggestions "${HOME}/zsh/plugins/zsh-autosuggestions"

# Installs zsh-shift-select plugin
echo "Installing zsh-shift-select..."
git clone --depth 1 --branch v0.1.1 https://github.com/jirutka/zsh-shift-select.git "${HOME}/zsh/plugins/zsh-shift-select"
