#!/usr/bin/env bash

# Installs pyenv dependencies.
sudo apt-get install \
python3-pip make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev

# Clones pyenv to ~/.pyenv directory.
git clone https://github.com/pyenv/pyenv.git ~/.pyenv
