#!/usr/bin/env python3

import sys
import re

order = {
    "##": 0,
    "A ": 1,
    " M": 3,
    "??": 2,
}

ansi_re = re.compile(r"\x1b[^m]*m")

print(
    "".join(
        sorted(
            sys.stdin.readlines(),
            key=lambda line: order.get(
                ansi_re.sub("", line)[0:2],
                0,
            ),
            reverse=1,
        )
    )
)
